### ISSUE TITLE
Proposal: Rename project to NubCore or Nub.js

### ISSUE THREAD

**Issue by creationix** [creationix/nucleus#23]
The word `nub` is nice and short. 

The definition is somewhat close.

> Nub: (noun) - the crux or central point of a matter

The name `nub` appears to be free on debian and darwin CLI namespaces.

https://twitter.com/trevnorris/status/742192091602640897

Thoughts?

**Comment by creationix** [comment]
The other option is just leave things as-is and ignore all the jokes about the TV show.

**Comment by ashleygwilliams** [comment]
i am personally not a fan. the slang definition is not good.

**Comment by creationix** [comment]
@ashleygwilliams right, though after searching for names, I've found that just about anything has a bad slang definition if you look hard enough.  I wish I knew how prevalent this slang definition was.

I'm open to other name suggestions, but would like to pick something and move on and get back to writing code and organizing a friendly community.

**Comment by ashleygwilliams** [comment]
i guess it personally makes me feel uncomfortable. i def prefer nucleus to nub. 

maybe something like gusset w/gus as the shortcut, or seam
or bazaar w/baz as shortcut

not sure, but def not a fan of nub

**Comment by creationix** [comment]
no problem, I'll try to find something else.

**Comment by rvagg** [comment]
I like nucleus, even with the pop-fiction overloading, in fact that kind of enhances it!

Of course you could go with PiedPiper or even EndFrame.

**Comment by creationix** [comment]
I think something around the word "light" would be awesome.  This project is the spark that starts bigger projects and we want a positive community. Also this core aims to be easy to understand as if light was shed upon the insides of larger projects.  (light has multiple meanings, yay)

**Comment by creationix** [comment]
@rvagg, thanks for that feedback.  I had assumed all relationship with the fictional project was negative, but it's good to know not everyone sees it that way.

**Comment by steveklabnik** [comment]
> I like nucleus, even with the pop-fiction overloading, in fact that kind of enhances it!
> 
> Of course you could go with PiedPiper or even EndFrame.

You do know that the show is completely making fun of how terrible our industry is, yes? Like, to the point where non-programmers assume that they're exaggerating, but they're not?

(I haven't posted yet because I myself have not come up with a good alternative yet, names are really hard. When @ashleygwilliams said "nub" to me, I giggled, though. Seems just as bad.)

**Comment by rvagg** [comment]
That's not lost on me but I'm far far away from SV so I get to laugh at it like the uneducated masses and not take it personally.

**Comment by yoshuawuyts** [comment]
`nucleus` with `nuke` as the shortcut?

**edit:** or `nuc` - pronounced "nook", which I think's a nice word

**Comment by creationix** [comment]
Keep in mind the length of this command isn't super important as you'll only use it when building your real CLI apps.

**Comment by creationix** [comment]
Thanks for the feedback everyone.  I've decided to keep the name.

This repo is now moved to the new org!
