### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by drom** [creationix/nucleus#3]
https://alpha.wallhaven.cc/wallpaper/271130

**Comment by creationix** [comment]
So 90's :)

**Comment by drom** [comment]
It is about 2014-2016:
2015: https://youtu.be/ddTbNKWw7Zs
2016: https://youtu.be/u48vYSLvKNQ

**Comment by creationix** [comment]
Oh my, time to rename the project. :P

**Comment by creationix** [comment]
Obviously I've not been keeping up with that show.  I do wonder how many people think of that as soon as they see this name.

**Comment by drom** [comment]
Let me see. Like ... 90% in Silicon Valley?
