### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Fishrock123** [creationix/nucleus#7]
I'd like there to be a License in place before I start contributing here.

In the event that this was useful enough to node to become part of the nodejs org, it may be prudent to license it under MIT as that is the easiest for us to take on. (Apache could be a better option, due to patents protection, and we'd no doubt also be ok with that. Many foundations seem to be.)

@creationix

**Comment by rvagg** [comment]
@creationix fwiw there's a lot of angst atm wrt MIT and what to do about it for patent protection, even talk of doing a CCLA for Node to cover it. The lawyers tell us that Apache would alleviate the problem because of the specific language included in the latest version. A proposal we have in front of us is to even do dual licensing for Node where commits into the future are covered by Apache and everything historically is MIT. You might want to look into this if you think this is going to go anywhere, they're saying that patents are the new battleground in open source licensing so expect it to become more pertinent.

**Comment by creationix** [comment]
@rvagg I don't have a strong opinion either way and have used Apache on the Luvit project for exactly this reason.  I initially chose MIT here because it was what node uses.  If node is trying to move to Apache, I'm fine with switching.

**Comment by Fishrock123** [comment]
@rvagg I had discussed that but we weren't sure it was actually that large of an issue considering it doesn't cover corporate CLA's? (Also re: updated node issues info)

**Comment by rvagg** [comment]
Yeah, I really don't know, my eyes glaze over when they talk about this stuff but my understanding was that Apache would help alleviate most of the concerns about patents and switching to it now would be ideal.

@mikeal, @jasnell ping, halp!

**Comment by jasnell** [comment]
Yes, Apache would be ideal given that it includes a patent license built
in.

There are two approaches to switching if there is pre-existing code:
1. Switch completely to Apache, in which case you must get all contributors
   to agree, or
2. Switch to Apache at a given point in time. All contributions up to that
   point are under the old license, all contributions after that point are
   under Apache.

With both it's easier to do it sooner than later.

**Comment by creationix** [comment]
@ashleygwilliams, @Fishrock123, @steveklabnik would any of you oppose to switching to Apache?

**Comment by Fishrock123** [comment]
I'm ok with switching.

**Comment by steveklabnik** [comment]
The usual Rust universe is dual licenced MIT/Apache2, I am fine with whatever open source or free software license you wish.

**Comment by mikeal** [comment]
Apache2 is a better license all around ;)

**Comment by Fishrock123** [comment]
@ashleygwilliams Could you please chime in on this?

**Comment by ashleygwilliams** [comment]
hi! sorry! i usually use MIT or ISC but i'm happy with whatever ya'll think is best.

**Comment by creationix** [comment]
Cool, sounds like everyone is cool with Apache.  I'll switch to that.

**Comment by creationix** [comment]
Done a78055aefe996a9ade787a9a438c06d06845dae7.
